export interface EmployeeModel {
    EmpProfileId: number
    AppUserName: string
    APIImagePath: string
    APIPath: string
    Extension: string
    FileName: string
    FullPath: string
    OriginalFileName: string
    First: string
    Middle: string
    Last: string
    Mail: string
    Phone: number
    Phone2: number
    Address: string
    Department: string
    EmployeeId: number
    BiomId: number
    EmerContact: number
    Languages: string
    JobTitle: string
    Nationality: string
    Gender: boolean
    MaritStatus: string
    Children: number
    DOB: string
    Supervisor: number
    DOJ: string
    ContractSt: string
    ContractEnd: string
    Education: string
    Experience: string
    Skills: string
    Trainings: string
    Certificates: string
    Basic: number
    Earn1: number
    Earn2: number
    Ded1: number
    Ded2: number
    Attachments: string
    Insurance: string
    InDesc: string
    InSt: any
    InEnd: any
    LaborCard: string
    LaborDesc: string
    LaborSt: any
    LaborEn: any
    EmiratesId: string
    EmiratesSt: any
    EmiratesEn: any
    Passport: string
    PassportSt: any
    PassportEn: any
    Visa: string
    VisaDesc: string
    VisaSt: any
    VisaEn: any
    IsTest: boolean
    Active: boolean
    Deleted: boolean
    UserCR: number
    Company: number
    RoleCR: number
    DateCR: string
    Browser: string
    Device: string
    Resol: string
    TransId: number
  }
  